set(ZIG_ROOT "$ENV{LOCALAPPDATA}/Microsoft/WinGet/Packages/zig.zig_Microsoft.Winget.Source_8wekyb3d8bbwe/zig-x86_64-windows-0.16.0")

set(CMAKE_C_COMPILER "${ZIG_ROOT}/zig.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_ARG1 "cc" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "${ZIG_ROOT}/zig.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_ARG1 "c++" CACHE STRING "" FORCE)

set(CMAKE_AR "${CMAKE_CURRENT_LIST_DIR}/../tools/zig-ar.cmd" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${CMAKE_CURRENT_LIST_DIR}/../tools/zig-ranlib.cmd" CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_AR "${CMAKE_CURRENT_LIST_DIR}/../tools/zig-ar.cmd" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_AR "${CMAKE_CURRENT_LIST_DIR}/../tools/zig-ar.cmd" CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_RANLIB "${CMAKE_CURRENT_LIST_DIR}/../tools/zig-ranlib.cmd" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_RANLIB "${CMAKE_CURRENT_LIST_DIR}/../tools/zig-ranlib.cmd" CACHE FILEPATH "" FORCE)